# Generated by Django 2.2.9 on 2020-01-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meituan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
