# Generated by Django 2.2.9 on 2020-02-05 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meituan', '0002_merchant_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=100, verbose_name='真实姓名')),
                ('telephone', models.CharField(max_length=11, verbose_name='手机号码')),
                ('province', models.CharField(max_length=100, verbose_name='省份')),
                ('city', models.CharField(max_length=100, verbose_name='城市')),
                ('county', models.CharField(max_length=100, verbose_name='区县')),
                ('address_detail', models.CharField(max_length=100, verbose_name='详细地址')),
                ('area_code', models.CharField(max_length=10, null=True, verbose_name='区域代号')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否是默认地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
