# Generated by Django 2.2.9 on 2020-07-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meituan', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
