# Generated by Django 2.2.9 on 2020-07-23 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meituan', '0007_auto_20200723_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='goods_list',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='meituan.Goods', verbose_name='商品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='meituan.Order', verbose_name='订单')),
            ],
        ),
    ]
